# Generated by Django 5.0.1 on 2024-01-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="upload",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="users/"
            ),
        ),
    ]
